{
 "title": "DB Node",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{mode!=\"idle\", job=\"db\", instance=\"10.104.0.2:9100\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=\"10.104.0.2:9100\",job=\"db\"}[5m])",
     "legendFormat": "{{device}} receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"api-service\",instance=\"159.65.135.45:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{job=\"db\", instance=\"10.104.0.2:9100\"} - node_memory_MemFree_bytes{job=\"db\", instance=\"10.104.0.2:9100\"} - node_memory_Cached_bytes{job=\"db\", instance=\"10.104.0.2:9100\"} - node_memory_Buffers_bytes{job=\"db\", instance=\"10.104.0.2:9100\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"api-service\", instance=\"159.65.135.45:9100\"}",
     "legendFormat": "Buffer"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"api-service\", instance=\"159.65.135.45:9100\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"api-service\", instance=\"159.65.135.45:9100\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=\"db\",instance=\"10.104.0.2:9100\",device!~\"/dev/loop.*\", device!~\"tmpfs|nsfs\", device!=\"gvfsd-fuse\"} - node_filesystem_avail_bytes{job=\"db\",instance=\"10.104.0.2:9100\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job=\"db\",instance=\"10.104.0.2:9100\",device!~\"/dev/loop.*\",device!~\"tmpfs|nsfs\",device!=\"gvfsd-fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}