global:
  scrape_interval: 5s
  evaluation_interval: 1m
# A scrape configuration scraping a node Exporter and the Prometheus server itself
scrape_configs:
  # Scrape Prometheus itself every 10 seconds.
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "api"
    static_configs:
      - targets: ["10.104.0.3:9100"]

  - job_name: "db"
    static_configs:
      - targets: ["10.104.0.2:9100"]

  # Note that this is a custom metrics that written in rcie-shopping-backend project which is different from the metrics from node-exporter
  - job_name: "api-golang"
    static_configs:
      - targets: ["10.104.0.3:8000"]
